package exceptionsHandling;

public class tryCatchAndFinally {

	public static void main(String[] args) 
	{
		
		
		String name="yadav";
		
		String a=null;
		
		try 
		{
			System.out.println(a.length());
			System.out.println(name.charAt(10));//risky code
		} 
		catch (NullPointerException e) 
		{
			System.out.println("we cant take any action on null value");
		}
		catch(StringIndexOutOfBoundsException e) 
		{
			System.out.println("please enter correct index value");
		}
		finally 
		{
			System.out.println("Hi I Am Ashok");
		}
		
		
		
		

	}

}
